### ISSUE TITLE
Refactor Events work

### ISSUE THREAD

**Issue by JackBekket** [MoonSHRD/IKY-telegram-bot#2]
```
	subscription, err := SubscribeForApplications(session,ch)

	EventLoop:
	for {
		select {
		case <-ctx.Done():
			{
			subscription.Unsubscribe();
			break EventLoop
			}
	case eventResult:= <-ch:
		{
			fmt.Println("/n")
			fmt.Println("User tg_id:", eventResult.ApplyerTg)
			fmt.Println("User wallet address:", eventResult.WalletAddress)

		}

		}
}
```

This code is working with subsciption at low level which is not necessary (and it doesn't work this way anymore), so we need to change `type` of it to `PassportPassportAppliedIterator`

Than instead of `subscribtion.Unsubscribe` use `Iterator.Close` and in case of incoming event use `Iterator.Next`, which will unpack and decode data we need

**Comment by JackBekket** [comment]
..And also we need to test it at local netwrork, so we also need to run IKY deployment in hardhat local net

**Comment by JackBekket** [comment]
Right now it's deployed in rinkeby and I have to redeploy it every time I want clean deploy

**Comment by JackBekket** [comment]
Annoying

**Comment by daseinsucks** [comment]
https://github.com/daseinsucks/eventListenerPassport/blob/master/main.go
Solved. Right now it **indeed** gets the data from events & deciphers it to readable values.

**Comment by daseinsucks** [comment]
I'm unsure though in which format you plan to store them, also I have no idea (_yet_) how to configure it to listen for two events at once.

**Comment by JackBekket** [comment]
> ```
> 	subscription, err := SubscribeForApplications(session,ch)
> 
> 	EventLoop:
> 	for {
> 		select {
> 		case <-ctx.Done():
> 			{
> 			subscription.Unsubscribe();
> 			break EventLoop
> 			}
> 	case eventResult:= <-ch:
> 		{
> 			fmt.Println("/n")
> 			fmt.Println("User tg_id:", eventResult.ApplyerTg)
> 			fmt.Println("User wallet address:", eventResult.WalletAddress)
> 
> 		}
> 
> 		}
> }
> ```
> 
> This code is working with subsciption at low level which is not necessary (and it doesn't work this way anymore), so we need to change `type` of it to `PassportPassportAppliedIterator`
> 
> Than instead of `subscribtion.Unsubscribe` use `Iterator.Close` and in case of incoming event use `Iterator.Next`, which will unpack and decode data we need

Note for myself
1. use `Iterator` type instead of direct subscription
2. use `WatchOpts`, not `FilterOpts`.   -- Filters is for past events (fast-forward), Watch is subscription for **new** events, we need last one in that particular case

**Comment by JackBekket** [comment]
Done

I still have to add security checks and I've found a weird bug in front-end, but at least now I've got any events I want and where I want
